#spring.profiles.active=test
spring.application.name=mongo-anime
#spring.data.mongodb.uri=mongodb://localhost:27017
spring.data.mongodb.uri=mongodb+srv://nvhai061993_db_user:HDUWnA30td9qp1Be@dhkhtn.xhtcoic.mongodb.net/dhkhtn?retryWrites=true&w=majority
spring.data.mongodb.database=dhkhtn
spring.profiles.active=default
#debug=true

#limit file size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

logging.level.root=INFO
logging.level.com.java.spring.movie_management=DEBUG
